<?php

require_once 'configDB.php';
require_once 'razorpay-php/Razorpay.php';

use Razorpay\Api\Api;

/*

*/

 $keyId = "rzp_test_rE3IOee1FdD1lN";
 $secretKey = '';
 $api = new Api($keyId,$secretKey);
 $PAY_AMT = "20000";
 $oid = "OWMC1234";
 
 
 $order = $api->order->create(array(
	'receipt' => $oid,
	'amount' => $PAY_AMT,
	'payment_capture' => 1,
	'currency' => 'INR',
	)
	);

?>
<html>
<head>
<script src="https://code.jquery.com/jquery-3.5.0.js"></script>
</head>

<body>
<form action="success.php" method="POST">
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="<?php echo $keyId; ?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="<?php echo $order->amount ?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"//You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-order_id="<?php echo $order->id ?>"//Replace with the order_id generated by you in the backend.
	data-orderid = "<?php echo $oid; ?>"
    data-buttontext="Pay with Razorpay"
    data-name="Test"
    data-description="Web Development"
    data-image="https://traidev.com/img/web-desgin-development.png"
    data-prefill.name="<?php echo $_POST['name'];?>"
    data-prefill.email="<?php echo $_POST['email'];?>"
    data-prefill.contact="<?php echo $_POST['mobile'];?>"
    data-theme.color="#F37254"
></script>
<input type="hidden" custom="Hidden Element" name="hidden">
</form>
</body>
</html>

