<?php

// require_once 'configDB.php';
require_once 'razorpay/razorpay-php/Razorpay.php';

use Razorpay\Api\Api;

/*
Key ID : rzp_test_rE3IOee1FdD1lN
Secret Key : SjhuOJjTmcXC0rhRAOfvRhVA


Live Key
Key ID : rzp_live_6Q0hFwn7CvrYsv
Secret Key : gfCAEjNyc1I2X1XetW8MCPgk

*/
// print_r($_POST);
 $keyId = "rzp_test_rE3IOee1FdD1lN";
 $secretKey = '';
 $api = new Api($keyId,$secretKey);
 



 



//  total payable payment
 $PAY_AMT =$_POST['pay_with_gst'] * 100;

 

 $oid = 'RMT'.date('dmY').rand(1000,9999);
 

//  Array ( [birthday] => 0 [pay_without_gst_coupon] => h-693 [coupon_id] => 0 [gst] => 123 [pay_with_gst_coupon] => 816 )

// [birthday] => 0 [pay_without_gst_coupon] => h-693 [coupon_id] => 14 [gst] => 123 [pay_with_gst_coupon] => 747
 

 $order = $api->order->create(array(
	'receipt' => $_POST['booking_id'],
	'amount' => $PAY_AMT,
	'payment_capture' => 1,
	'currency' => 'INR',
	)
    );
    
 


$array=array(
    'payment_status' =>  "f",
    'previews_payment'=>$_POST['previews_payment'],
    'bid' => $_POST['bid'],
    'booking_id' =>  $_POST['booking_id'],
    'pay_with_gst'=>$_POST['pay_with_gst']  
);

$this->session->set_userdata('p_rp_payment_details',$array);

// echo "<pre>";
// print_r($this->session->userdata('p_rp_payment_details'))




    

?>



<form action="<?=base_url().'booking_list/p_paymentsucnew'?>" method="POST">

<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="<?php echo $keyId; ?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="<?php echo $order->amount ?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"//You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-order_id="<?php echo $order->id ?>"//Replace with the order_id generated by you in the backend.
	data-orderid = "<?php echo $oid; ?>"
    data-buttontext="Pay with Razorpay"
    data-name="Hotelmate"
    data-description="Hotel Booking"
    data-image="https://traidev.com/img/web-desgin-development.png"
    data-prefill.name="<?php echo $u_fullname?>"
    data-prefill.email="<?php echo $u_email?>"
    data-prefill.contact="<?php echo $u_mobile;?>"
    data-theme.color="#F37254"
>
</script>

</form>